### ISSUE TITLE
FV Authenticated Restarts

### ISSUE THREAD

**Issue by ryangball** [ryangball/nice-updater#1]
Provide mechanism for FV Authenticated Restarts

**Comment by chadswarthout** [comment]
https://derflounder.wordpress.com/2018/03/29/new-automated-restart-option-added-to-10-13-4s-softwareupdate-command-line-tool/

`softwareupdate --install --all --restart`

**Comment by ryangball** [comment]
@chadswarthout This is probably the route I’ll have to take. I have to work out the logic for sub-10.13.4 Macs as well.

**Comment by ryangball** [comment]
Functional for 10.13.4 and above Macs with #9.
