### ISSUE TITLE
Install Latest Yo Failed

### ISSUE THREAD

**Issue by ZJPat** [ryangball/nice-updater#12]
Hello, if you try to install Yo using the Install_Latest_Yo.sh it fails with the error below. 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range
curl: (3) <url> malformed
installer: Error - the package path specified was invalid: '/tmp/yo.pkg'.
Yo installation failed; exiting.

If you go and check SheaCraig Yo repo, you will notice the latest release doesn't have a compiled pkg file.

**Comment by peterlewis** [comment]
Yup. Looks to be the case. From my understanding without a pre-built binary within the Yo repository, the script won't work. I can see two solutions:

1. Ask @sheagcraig to upload a binary for [2.0.2](https://github.com/sheagcraig/yo/releases/tag/2.0.2)
2. Host a pre-built binary elsewhere which Install_Latest_Yo.sh can then reference.

I'd suggest 1, personally... Thoughts, @ryangball?

**Comment by ryangball** [comment]
I could just change this line:
`latestYoReleaseURL=$(curl -s https://api.github.com/repos/sheagcraig/yo/releases/latest |  python -c 'import json,sys;obj=json.load(sys.stdin);print obj["assets"][0]["browser_download_url"];');`

to

`latestYoReleaseURL="https://github.com/sheagcraig/yo/releases/download/2.0.1/yo-2.0.1.pkg"`

to get the last release. Seem okay?

**Comment by ryangball** [comment]
Fixed to use latest release pkg in 37170191fb7704f6a2b99ba35a495efe9353830c.
